
on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '*/5 * * * *'

env:
  ACRNAME: openhackcgb03xk8acr
  RESOURCE_GROUP: openhackcgb03xk8rg
  
jobs:
  revertSwap:
    name: Delte userjava
      # needs:
      #     - healthcheck-staging
    runs-on: ubuntu-latest
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Delete resource
        uses: azure/CLI@v1
        with:
          azcliversion: 2.23.0
          inlineScript: |
            echo "running auto swap"
            az webapp deployment slot delete \
            --name openhackcgb03xk8userjava \
            --resource-group ${{env.RESOURCE_GROUP}} \
            --slot staging

