name: .NET

on:
  push:
    branches: [ master ]
    paths:
      - "apis/poi/**"
  pull_request:
    branches: [ master ]
    paths:
      - "apis/poi/**"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1.7.2
      with:
        dotnet-version: 2.1.x
    - name: Restore dependencies
      run: dotnet restore  apis/poi/
    - name: Build
      run: dotnet build --no-restore apis/poi/
    - name: Test
      run: dotnet test --no-build --verbosity normal apis/poi/
    - name: Docker Build
      run: docker build apis/poi/web
