# This is a basic workflow to help you get started with Actions
name: PR User-java

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
     paths:
      - 'apis/user-java/**'
  pull_request:
    branches: [ master ]


#on: push

jobs:
  quality-java:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build with Maven
        run: mvn build
      - name: Quality
        run: |
          mvn test
