# This is a basic workflow to help you get started with Actions
name: PR POI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  pull_request:
    branches: 
      - master
    paths:
      - 'apis/poi/**'

#on: push

jobs:
  quality-cs:    
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build
      - name: Test with the dotnet CLI
        run: dotnet test
        
        
      - name: Assign issues to project
        if: failure()
        uses: technote-space/create-project-card-action@v1
        with:
          PROJECT: OpenHack
          COLUMN: To do
          repo-token: ${{ secrets.GITHUB_TOKEN }}

        
